security:
    enable_authenticator_manager: true
    providers:
        user:
            entity: { class: App\Entity\User, property: username }
        admin:
            entity: { class: App\Entity\Admin, property: username }
    password_hashers:
        App\Entity\User:
            algorithm: auto
            cost: 15
        App\Entity\Admin:
            algorithm: auto
            cost: 15
    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|img|js)/
            security: false
        user:
            provider: user
            pattern: ^(/$|/user|/teacher|/student|/administration|/page|/home/|/home$)
            lazy: true
            custom_authenticator: App\Security\Auths\UserLoginFormAuthenticator
            logout:
                path: user_logout
                target: login
        admin:
            provider: admin
            pattern: ^/admin_74ze5f
            lazy: true
            custom_authenticator: App\Security\Auths\AdminLoginFormAuthenticator
            logout:
                path: admin_logout
                target: admin_login
    access_control:
        - { path: ^/admin_74ze5f/login$, roles: PUBLIC_ACCESS }
        - { path: ^/admin_74ze5f/logout$, roles: PUBLIC_ACCESS }
        - { path: ^/admin_74ze5f, roles: [ROLE_ADMIN, ROLE_SUPER_ADMIN] }
        - { path: ^/user/login$, roles: PUBLIC_ACCESS }
        - { path: ^/user/register, roles: PUBLIC_ACCESS }
        - { path: ^/user/password/reset/[A-Za-z0-9]+$, roles: PUBLIC_ACCESS }
        - { path: ^/api/login_check/, roles: PUBLIC_ACCESS }
        - { path: ^/user/, roles: [ROLE_USER, ROLE_ADMIN] }
        - { path: ^/admin/, roles: ROLE_ADMIN }
        - { path: ^/student/, roles: ROLE_STUDENT }
        - { path: ^/teacher/, roles: ROLE_TEACHER }
        - { path: ^/, role: PUBLIC_ACCESS }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Lowest possible value for bcrypt
                time_cost: 3 # Lowest possible value for argon
                memory_cost: 10 # Lowest possible value for argon
